### ISSUE TITLE
Riconnessione automatica

### ISSUE THREAD

**Issue by matteosirri** [progamma/cloud-connector#23]
Al momento se si perde la connessione verso un server non c'è nessun automatismo di riconnessione.

**Comment by andreamaioli** [comment]
per tenere traccia nel complessivo di questi issue, può essere utile copiarli anche nel "calderone" globale?

**Comment by matteosirri** [comment]
Ho verificato che quando si perde la connessione verso un server la socket tenta di riconnettersi in automatico
